<?php

namespace AppBundle\Repository;

/**
 * ShiftTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
